core/Design_Site/urls.py
from django.urls import path
from .views import *




app_name = 'Design_Site'
urlpatterns = [
    # path('', views.index, name='index')
    path('', HomeView.as_view(), name="index"),

]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('Design_Site/', include('Design_Site.urls')),
    path('admin/', admin.site.urls),
    
]

core/Design_Site/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Intro(models.Model):
    title = models.CharField(max_length=50, null=True)
    description = models.TextField(max_length=500)

    def __str__(self):
        return self.title

class Customer(models.Model):
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, null=True)
    phone = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    # Category tuple
    CATEGORY =(
        ('BC', 'Business Card'),
        ('BR', 'Brochure'),
        ('FR', 'Flyer'),
        ('PR', 'Poster'),
        ('WI', 'Wedding Invitation'),
        
    )
    name = models.CharField(max_length=200, null=True)
    price = models.FloatField(null=True)
    category = models.CharField(max_length=200, null=True, choices=CATEGORY)
    description = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

     

core/Design_Site/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.views.generic import TemplateView, DetailView

from .models import *
# Create your views here.


# def index(request):
#     return render(request, "index.html")


class HomeView(TemplateView):
    template_name = "index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['intros'] = Intro.objects.all()[:3]
        return context

core/Design_Site/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>747 Designs | Home</title>
    <!-- Bootstrap CSS CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!--CSS FIles-->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <!-- <link rel="stylesheet" href="{% static 'css/cover.css' %}"> -->

    <title>{% block head_title %}{% endblock %}</title>
    <!-- <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style> -->
  </head>

  <body>

    {% include 'nav.html' %}

      {% block content %}
      
      {% endblock %}

     <!--footer--> 
    {% include 'footer.html' %}

    <!--Scripts--> 
     {% include "scripts.html" %}
     {% block extra_scripts %}
     {% endblock %}
  </body>
</html>

core/Design_Site/templates/footer.html
<footer class="container footer mx-auto py-3">
  <p class="float-right"><a href="#">Back to top</a></p>
  <p>
    &copy; 2018-2019 747 Designs & Prints, Inc. &middot;
    <a href="#">Privacy</a> &middot; <a href="#">Terms</a>
  </p>
</footer>

core/Design_Site/templates/index.html
{% extends 'base.html' %} {% block content %}
<br />
<br />
<!--Jumbotron-->
<div class="row">
  <div class="col">
    <div class="jumbotron">
      <div class="container">
        <h1 class="display-4 text-muted font-weight-bold">
          747 Designs & Prints
        </h1>
        <h4 class="text-capitalize">
          Innovate Your Ideas and bring them to life!
        </h4>
        <p>
          <a
            class="btn btn-outline-primary btn-lg btn-round"
            href="#"
            role="button"
            >Learn more &raquo;</a
          >
        </p>
      </div>
    </div>
  </div>
</div>

<section class="intro py-4">
  <!--Heading Flexbox-->
  <div class="col text-center">
    <h1 class="text-uppercase text-muted mb-1">
      <strong>what do we do?</strong>
    </h1>
    <div class="title-underline bg-warning"></div>
  </div>

  <!--Intros-->
  <div class="container mt-5">
    <div class="row">
      <!--Intro Col-->
      {% for intro in intros %}
      <div class="col-md-4">
        <h1>{{intro.title}}</h1>
        <p class="lead text-left">{{intro.description}}</p>
      </div>
      {% endfor %}
    </div>
  </div>
</section>

<section class="contentbody bg-light py-5">
  <div class="row">
       <div class="col-md-7">
        <h2 class="featurette-heading text-muted">Featurette.</h2>
      
      </div>
      <div class="col-md-5">
        <div class="card mdl-shadow--4dp">
          <img class="featurette-image img-fluid  mx-auto" src="img/jay.jpg" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
          <div class="card-body">
            <h5 class="card-title text-capitalize text-muted d-flex justify-content-center">
              Javon Browne
            </h5>

          </div>
          <!-- card footer-->
          <div class="card-footer bg-info d-flex justify-content-around">
            <a href="#"><i class="fab fa-facebook fa-2x text-light"></i></a>
            <a href="#"><i class="fab fa-twitter fa-2x text-light"></i></a>
            <a href="#"><i class="fab fa-youtube fa-2x text-light"></i></a>
            <a href="#"><i class="fab fa-google fa-2x text-light"></i></a>
          </div>
          <!-- end of card footer -->
        </div>
      </div>
  </div>

</section>

{% endblock %}

core/Design_Site/templates/nav.html
<!--Navbar-->
<!-- <header class="masthead mb-auto">
  <div class="inner">
    <h3 class="masthead-brand"><a class="text-light" href="{% url  'Design_Site:index' %}">747 Designs & Prints</a></h3>
    <nav class="nav nav-masthead justify-content-center">
      <a href="" class="nav-link active">Home</a>
      <a href="" class="nav-link">About</a>
      <a href="" class="nav-link">Contact</a>
    </nav>
  </div>
</header> -->

<nav class="navbar navbar-expand-lg fixed-top navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'Design_Site:index' %}">747 Designs & Prints</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">About</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Products
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Business Cards</a>
          <a class="dropdown-item" href="#">Flyers</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Posters</a>
          <a class="dropdown-item" href="#">Wedding Invitation</a>
        </div>
      </li>
      <!-- <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li> -->
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2 btn-round" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success btn-round my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

core/Design_Site/templates/scripts.html
{% load static %}
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->

<script
  src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
  integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
  crossorigin="anonymous"
></script>
<script
  src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
  integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
  crossorigin="anonymous"
></script>
<script
  src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
  integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
  crossorigin="anonymous"
></script>

<!--local Javascript-->
<!--local Jquery-->
<!-- <script
  type="text/javascript"
  src="{% static 'js/jquery-3.4.1.min.js' %}"
></script>

<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>

<script
  type="text/javascript"
  src="{% static 'js/bootstrap.min.js' %}"
></script> -->